################################################################################
# Configuration for coveralls.
# Author: Petra Barus <petra.barus@gmail.com>
################################################################################
coverage_clover: build/logs/clover.xml
