language: php
dist: trusty
apt:
    packages:
        ruby-coveralls

php:
    - 5.5
    - 5.6
    - hhvm
    - 7

before_install:
    composer self-update

install:
    composer install

script:
    ./vendor/bin/phing

after_success:
    coveralls
